-- Fuentes de datos Excel
INSERT INTO fuentes_vin (tipo_fuente, ruta_patron, columna_vin, activo) VALUES
  ('Reporte Fichas',          'Reporte_fichas_*', 'Vin', true),
  ('Reporte Inmatriculación', 'Reporte_Inma_*',   'Vin', true),
  ('Proped',                  'PROPED BUSES*',    'VIN', true)
ON CONFLICT DO NOTHING;

-- Mapeo de columnas Excel → staging_vin
-- id_fuente: 1=Reporte Fichas, 2=Reporte Inmatriculación, 3=Proped
-- Solo campos no-fecha / no-hito

INSERT INTO mapeo_campos_vin (nombre_campo, id_fuente, nombre_columna_fuente, prioridad, activo) VALUES
  -- ── Reporte Fichas / SAP (fuente 1) ──
  ('cond_pago',             1, 'Cond. De pago',        1, true),
  ('descripcion_cond_pago', 1, 'Descripción Cond pag', 1, true),
  ('lote_asignado',         1, 'Lote.Asignado',        1, true),
  ('id_ficha_sap',          1, 'Id.Ficha',             1, true),
  ('pedido_externo',        1, 'Pedido Externo',       2, true),
  ('pedido_venta_sap',      1, 'Pedido Venta',         1, true),
  ('num_factura_sap',       1, 'Num Factura',          1, true),
  ('modelo_comercial',      1, 'Modelo Comercial',     1, true),
  ('modelo_facturacion',    1, 'Modelo Facturación',   1, true),
  ('num_declaracion',       1, 'N° Declaración',       1, true),
  ('nombre_cliente_sap',    1, 'Descr.Cliente',        1, true),
  ('cod_cliente_sap',       1, 'Cliente',              1, true),
  ('cod_vendedor',          1, 'Vendedor',             1, true),
  ('nombre_vendedor',       1, 'Descr.Vendedor',       1, true),
  ('status_compra_sap',     1, 'Status Compra',        1, true),
  ('estado_ficha_sap',      1, 'Estados',              1, true),
  ('precio_venta_pv',       1, 'Precio Venta PV',      1, true),
  ('precio_lista',          1, 'Precio Lista',         1, true),
  ('sku',                   1, 'ZSKU',                 1, true),
  ('matricula',             1, 'Matr.vehículo',        1, true),

  -- ── Proped (fuente 3) ──
  ('num_factura_comex',     3, 'NUMERO FACTURA',                    1, true),
  ('precio_confirmado',     3, 'PRECIO CONFIRMADO',                 1, true),
  ('pedido_interno',        3, 'PEDIDO INTERNO',                    1, true),
  ('pedido_externo',        3, 'PEDIDO EXTERNO',                    1, true),
  ('linea_negocio',         3, 'LINEA DE NEGOCIO',                  1, true),
  ('carrocero',             3, 'CARROCERO',                         1, true),
  ('cliente_comex',         3, 'CLIENTE ',                          1, true),
  ('estado_comex',          3, 'ESTADO',                            1, true),
  ('modalidad_embarque',    3, 'MODALIDAD',                         1, true),
  ('transportista',         3, 'EMBARQUE',                          1, true),
  ('remonta',               3, 'REMONTA',                           1, true),
  ('dias_prod_carr_planif', 3, 'DIAS PROD PLANIF',                  1, true),
  ('dias_prod_carr_real',   3, 'DIAS PROD REAL',                    1, true),
  ('observaciones_comex',   3, 'Observaciones',                     1, true),

  -- ── Reporte Inmatriculación (fuente 2) ──
  ('situacion_inmatric',    2, 'Situacion de Imatric',  1, true),
  ('fecha_inicio_inmatric', 2, 'Fecha Inicio Inmatri',  1, true),
  ('fecha_titulo',          2, 'Fecha Titulo',          1, true),
  ('numero_titulo',         2, 'Número Titulo',         1, true),
  ('placa',                 2, 'Placa',                 1, true),
  ('fecha_inscrito',        2, '013 Inscrito',          1, true),
  ('fecha_rep_placa',       2, '026 Rep Placa',         1, true),
  ('fecha_rec_doc_car',     2, '002 Rec.Doc Car',       1, true),
  ('fecha_rec_doc',         2, '003 Rec.Doc',           1, true),
  ('fecha_em_doc',          2, '001 Em.Doc',            1, true),
  ('fecha_obs_app',         2, '061 Obs.App',           1, true),
  ('fecha_cal_sunarp',      2, '007 Cal.Sunarp',        1, true),
  ('oficina_registral',     2, 'Oficina Registral',     1, true),
  ('fecha_maxima_tramite',  2, 'Fecha Maxima Tramite',  1, true),
  ('fecha_cancelacion',     2, 'Fecha Cancelación',     1, true),
  ('folio',                 2, 'Folio',                 1, true),
  ('clase_operacion',       2, 'Clase de operación',    1, true),
  ('color',                 2, 'Color',                 1, true),
  ('cod_color',             2, 'Cod.Color',             1, true),
  ('tapiz',                 2, 'Tapiz',                 1, true),
  ('cod_tapiz',             2, 'Cod_tapiz',             1, true),
  ('d_canal',               2, 'D.Canal',               1, true),

  -- ── Reporte Inmatriculación (fuente 2) — campos compartidos (prioridad 2) ──
  ('num_factura_sap',       2, 'Num Factura',          2, true),
  ('num_declaracion',       2, 'N° Declaración',       2, true),
  ('nombre_cliente_sap',    2, 'Descr.Cliente',        2, true),
  ('id_ficha_sap',          2, 'Id.Ficha',             2, true),
  ('nombre_vendedor',       2, 'Descr.Vendedor',       2, true),
  ('modelo_facturacion',    2, 'Modelo Facturación',   2, true),
  ('estado_ficha_sap',      2, 'Estados',              2, true),
  ('modelo_comercial',      2, 'Modelo Comercial',     2, true),
  ('matricula',             2, 'Matr.vehículo',        2, true),
  ('lote_asignado',         2, 'Lote.Asignado',        2, true),
  ('pedido_externo',        2, 'Pedido Externo',       3, true),
  ('cod_cliente_sap',       2, 'Cliente',              2, true),
  ('cod_vendedor',          2, 'Vendedor',             2, true),
  ('pedido_venta_sap',      2, 'Pedido Venta',         2, true),
  ('status_compra_sap',     2, 'Status Compra',        2, true),
  ('sku',                   2, 'ZSKU',                 2, true),
  ('fecha_asignacion',      2, 'Fecha Asignación',     2, true),
  ('fcl',                   2, 'FCL',                  2, true),
  ('fcc',                   2, 'FCC',                  2, true),
  ('fcr',                   2, 'FCR',                  2, true),
  ('fclr',                  2, 'FCLR',                 2, true),
  ('fecha_facturacion_sap', 2, 'Fecha Facturación',    2, true),
  ('fecha_entrega_cliente', 2, 'ENTREGA',              2, true),
  ('fecha_embarque_sap',    2, 'Fecha Embarque',       2, true),
  ('fecha_llegada_sap',     2, 'Fecha Llegada',        2, true),
  ('fecha_aduana_sap',      2, 'Fecha Aduana',         2, true),
  ('fecha_nacion',          2, 'Fecha Nación',         2, true),
  ('fecha_preasignacion',   2, 'Fecha.Preasignacion',  2, true)
ON CONFLICT DO NOTHING;
